version: '3'
volumes:
  shared-volume:
services:
  eLearning_build:
    image:  vue_firebase
    container_name: eLearning_build
    restart: on-failure
    ports:
      - 5555:3000
    command:
        - /bin/bash
        - -c
        - |
          npm run build
          ls /app/dist
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./vite.config.js:/app/vite.config.js
      - ./index.html:/app/index.html
      - shared-volume:/app/dist
  nginx_server:
    image:  nginx
    container_name: nginx_serve_vue
    restart: on-failure
    ports:
      - 8888:80
    volumes:
      - shared-volume/:/usr/share/nginx/html/ 
    depends_on:
      - eLearning_build    